
package server;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "TestMtomPortType", targetNamespace = "http://cxf.apache.org/mime")
public interface TestMtomPortType {


    /**
     * 
     * @param attachinfo
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "testByteArray", targetNamespace = "http://cxf.apache.org/mime/types", className = "org.apache.cxf.mime.types.ByteArrayType")
    @ResponseWrapper(localName = "testByteArrayResponse", targetNamespace = "http://cxf.apache.org/mime/types", className = "org.apache.cxf.mime.types.ByteArrayType")
    public void testByteArray(
        @WebParam(name = "name", targetNamespace = "http://cxf.apache.org/mime/types", mode = WebParam.Mode.INOUT)
        Holder<String> name,
        @WebParam(name = "attachinfo", targetNamespace = "http://cxf.apache.org/mime/types", mode = WebParam.Mode.INOUT)
        Holder<byte[]> attachinfo);

    /**
     * 
     * @param attachinfo
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "testDataHandler", targetNamespace = "http://cxf.apache.org/mime/types", className = "org.apache.cxf.mime.types.DataHandlerType")
    @ResponseWrapper(localName = "testDataHandlerResponse", targetNamespace = "http://cxf.apache.org/mime/types", className = "org.apache.cxf.mime.types.DataHandlerType")
    public void testDataHandler(
        @WebParam(name = "name", targetNamespace = "http://cxf.apache.org/mime/types", mode = WebParam.Mode.INOUT)
        Holder<String> name,
        @WebParam(name = "attachinfo", targetNamespace = "http://cxf.apache.org/mime/types", mode = WebParam.Mode.INOUT)
        Holder<DataHandler> attachinfo);

}
